### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by pwldp** [pyatom/pyatom#105]
I've installed atomac on OS X Yosemite:

```
sudo easy_install atomac
```

 Run python and import atomac and got an error:

```
bash-3.2$ python
Python 2.7.8 (default, Oct  3 2014, 02:34:26) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import atomac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/atomac-1.1.0-py2.7-macosx-10.8-intel.egg/atomac/__init__.py", line 18, in <module>
  File "/Library/Python/2.7/site-packages/atomac-1.1.0-py2.7-macosx-10.8-intel.egg/atomac/_a11y.py", line 7, in <module>
  File "/Library/Python/2.7/site-packages/atomac-1.1.0-py2.7-macosx-10.8-intel.egg/atomac/_a11y.py", line 3, in __bootstrap__
ImportError: No module named pkg_resources
```

Whats wrong?

**Comment by nagappan** [comment]
A quick search in google yields me this as a result - http://stackoverflow.com/questions/22148144/python-importerror-no-module-named-pkg-resources
