### ISSUE TITLE
Unable to use atomac in mac 10.10

### ISSUE THREAD

**Issue by lokeshksymantec** [pyatom/pyatom#106]
Steps for reproducibility : 
1)installed atomac - using command in terminal - sudo pip install atomac
2)Tried to import atomac in python (2.7.8) - but thrown with error : 

> > > import atomac
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "build/bdist.macosx-10.10-x86_64/egg/atomac/**init**.py", line 20, in <module>
> > >   File "build/bdist.macosx-10.10-x86_64/egg/atomac/AXClasses.py", line 19, in <module>
> > > ImportError: No module named AppKit
> > > 3)Tried to install the module Appkit through : sudo easy_install -U pyobjc
> > > Error obtained : raise CalledProcessError(retcode, cmd, output=output)
> > > subprocess.CalledProcessError: Command '['/usr/bin/xcodebuild', '-version', '-sdk', 'macosx', 'Path']' returned non-zero exit status 1
> > > 4)Tried another way to install the module Appkit through : sudo pip install pyobjc
> > > Error Obtained: 
> > > Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/pyobjc-core
> > > Storing debug log for failure in /Users/admin/.pip/pip.log

**Comment by sushantgupta** [comment]
How to enable systemwide accessibility on 10.10.1(yosemite).
Systemwide accessibility must be enabled. Check the checkbox: System Preferences > Universal Access > Enable access for assistive devices. Failure to enable this will result in ErrorAPIDisabled exceptions during some module usage.

**Comment by morozgrafix** [comment]
I was also getting `ImportError: No module named AppKit` error when attempting to `import atomac`

Followed instructions on http://pythonhosted.org/pyobjc/install.html to get pyobjc installed.

After running: 

    sudo pip install -U pyobjc-core
    sudo pip install -U pyobjc

I was able to import atomac successfully.

**Comment by morozgrafix** [comment]
@sushantgupta As far as I know there is no systemwide accessibility for OS X since Mavericks, I believe that was switched to per app permissions model. http://support.apple.com/en-us/HT202866 but there may be a workaround (although I haven't tested it yet) described here: http://support.apple.com/en-us/HT202802

**Comment by mzy12345** [comment]
Systemwide accessibility had been removed since Mavericks. When I import atomac in Python interpreter for the first time, there would be a dialog telling you that "Terminal would like to control this computer using accessibility features", I open the System Preference > Security Privacy > Privacy > Accessibility and grant the access to Terminal. After that, atomac could work in Python interpreter. So I guess it's no necessary to enable systemwide accessibility, just add Terminal to the accessibility control list is okay.

**Comment by priyasekar015** [comment]
Thanks @morozgrafix: ur fix worked like a charm :)
