### ISSUE TITLE
problems testing a java GUI: can't switch tabs in a JTabbedPane

### ISSUE THREAD

**Issue by mmpcn** [pyatom/pyatom#115]
For example, using the java demo code from: http://docs.oracle.com/javase/tutorial/uiswing/examples/components/TabbedPaneDemoProject/src/components/TabbedPaneDemo.java

you get as many unknown objects as the number of tabs: 
getobjectlist("TabbedPaneDemo")
['ukn2', 'ukn3', 'ukn0', 'ukn1', 'btnzoombutton', 'btnminimizebutton', 'btnclosebutton', 'ptlTab1', 'lblPanel#1', 'lblTabbedPaneDemo']

getobjectproperty("TabbedPaneDemo", 'ptlTab1', 'children')
'ukn0 ukn1 ukn2 ukn3 lblPanel#1'

where the ukn* objects have no defined class. 

I tried to select a tab index, but:

selecttabindex("TabbedPaneDemo", 'ptlTab1', 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.9-intel/egg/atomac/ldtp/client.py", line 80, in __call__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "build/bdist.macosx-10.9-intel/egg/atomac/ldtp/client.py", line 204, in request
xmlrpclib.Fault: <Fault 1: "<class 'atomac._a11y.ErrorInvalidUIElement'>:Error retrieving attribute (AXError -25202)">

**Comment by nagappan** [comment]
Can you see the Java window widgets through Accessibility inspector ? If they are visible there and not through pyatom, then its bug in pyatom. If its not visible to accessibility inspector, then you need to fix the software to export accessibility info.

https://developer.apple.com/library/mac/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTesting/OSXAXTestingApps.html

**Comment by ladza** [comment]
Indeed, it is most likely what Nahappan said. Some UI elements in your application do not have AXRole and AXTitle set. You need to implement those accessibility attributes in order to see it correctly displayed in atomac/ldtp. Moreover some AXRoles are not recognized by atomac at the moment ( for example AXPopover). I will add those roles, when I have a spare moment.

**Comment by mmpcn** [comment]
Hi,

thanks for the link  about the Accessibility Inspector.

On 30 Jan 2015, at 05:08, Nagappan Alagappan <notifications@github.com> wrote:

> Can you see the Java window widgets through Accessibility inspector ? If they are visible there and not through pyatom, then its bug in pyatom. If its not visible to accessibility inspector, then you need to fix the software to export accessibility info.
> 
I used the Inspector and found some differences - I still don't know if the problem is with my implementation or not:

The Accessibility Inspector showed an AXTabGroup element, and below it an AXRadioButton element (which should be one of the tabs)

ldtp.getobjectlist() does not show any radioButton element.


But the Accessibility Inspector shows also something strange - the AXRadioButton element has AXTabGroup element as Parent, but
the AXTabGroup element does not list it as a child.

I'm still trying to find out how to export the accessibility info of a JTabbedPane element. I can set AXName and AXTitle, but nothing about the selection.  Any hint will be appreciated!

Margarida

-- 
Margarida Castro Neves

Astronomisches Rechen-Institut (ARI)
Zentrum für Astronomie, Universität Heidelberg  (ZAH)
Mönchhofstr. 12 - 14, 69120 Heidelberg
phone +49-6221-54-1891   fax +49-6221-54-1888
mcneves@ari.uni-heidelberg.de
http://www.ari.uni-heidelberg.de
