### ISSUE TITLE
can import atomac on Yosemite. AppKit seems to be renamed as appkit. 

### ISSUE THREAD

**Issue by chracing** [pyatom/pyatom#118]
>>> import atomac.ldtp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/atomac/__init__.py", line 20, in <module>

  File "build/bdist.macosx-10.10-x86_64/egg/atomac/AXClasses.py", line 19, in <module>
ImportError: No module named AppKit

Grip of code base shows 2 imports of AppKit
AXClasses.py:import AppKit
Clipboard.py:import AppKit

**Comment by nagappan** [comment]
Can you provide a quick patch ? will update git main. I haven't updated my mac yet, it's due quite a while. Thanks

**Comment by ladza** [comment]
I used atomac on 10.10 and to be honest I do remember having any issues with it. It seems like a environment configuration issue. Have you checked if you are able to import AppKit manually?
Run python and in the interactive console execute import AppKit.

**Comment by bzzzzzz** [comment]
AppKit is imported without problems on Mac OS X 10.10:

    $ python
    Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import AppKit
    >>> 

Probably, you have installed pyatom package in virtual environment, so you need also install pyobjc package. 

btw. pyobjc is not listed in pyatom requirements, maybe I should provide a patch to fix it?

**Comment by nagappan** [comment]
Ya that will be nice, thanks :-)
