### ISSUE TITLE
Cannot click on UI when using atomac.ldtp on OS X Yosemite

### ISSUE THREAD

**Issue by cristeab** [pyatom/pyatom#130]
Hi

I am having difficulties using atomac.ldtp when I try to click on an existing object. getobjectlist() returns a list of objects where I can see the object I want to click on, then, when I use click() on that object, I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/atomac-1.1.0-py2.7-macosx-10.8-intel.egg/atomac/ldtp/client.py", line 74, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/Library/Python/2.7/site-packages/atomac-1.1.0-py2.7-macosx-10.8-intel.egg/atomac/ldtp/client.py", line 195, in request
    raise e
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.IndexError'>:list index out of range">

This behaviour appears immediately when I try to use atomac.ldtp, but it can disappear after a while and I am able to click correctly on that object.

The application I test is written in Qt 5.4 with QML for the UI.

regards
Bogdan

**Comment by nagappan** [comment]
Is this based on atomac pip package or from git head ?

**Comment by cristeab** [comment]
It is from atomac pip package

**Comment by nagappan** [comment]
Can you try this from git head and try ?

**Comment by cristeab** [comment]
Now when I try to import atomac in Python I get:

>>> import atomac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "atomac/__init__.py", line 19, in <module>
    from _a11y import Error, ErrorAPIDisabled, ErrorInvalidUIElement, \
ImportError: No module named _a11y

**Comment by johnsayeau** [comment]
I'm getting the same error as above. I used the zip from this git head

**Comment by nagappan** [comment]
I cloned a fresh copy in /tmp and then compiled/installed, everything went fine on OS X Yosemite. Not sure why you are hitting this issue.

**Comment by alexgh3** [comment]
Do you have accessibility enabled or Xcode installed? This might help: http://l34rn-p14y.blogspot.ro/2014/11/simple-automation-using-python-atomac.html
