### ISSUE TITLE
atomac._a11y.ErrorCannotComplete: Error performing requested action (AXError -25204) on pressing popup

### ISSUE THREAD

**Issue by kirillzhukov-cc** [pyatom/pyatom#131]
On calling Press() and ShowMenu() popUpButton is being pressed but after 2-3 seconds next exception is raised:
```python
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/kirill/workspace/personal/python/Sandbox/test.py
Traceback (most recent call last):
  File "/Users/kirill/workspace/personal/python/Sandbox/test.py", line 62, in <module>
    popUpButton.Press()
  File "/Library/Python/2.7/site-packages/atomac/AXClasses.py", line 701, in performSpecifiedAction
    return self._performAction(name)
  File "/Library/Python/2.7/site-packages/atomac/AXClasses.py", line 497, in _performAction
    _a11y.AXUIElement._performAction(self, 'AX%s' % action)
atomac._a11y.ErrorCannotComplete: Error performing requested action (AXError -25204)
```

**Comment by ashwinganesh29** [comment]
I am getting into the same issue.  did you figure out why this is happening?

**Comment by kirillzhukov-cc** [comment]
@ashwinganesh29, as I remember I just caught and ignored this exception. Timeout is the only problem.

**Comment by ashwinganesh29** [comment]
Thanks for the response. Where you able to access the menu after that? I have not been able to do that too?
