### ISSUE TITLE
simple LDTP example does not work

### ISSUE THREAD

**Issue by sglebs** [pyatom/pyatom#143]
Hello. I followed the example in the README and tried something very simple:

```
try:
    import ldtp
except ImportError:
    import atomac.ldtp as ldtp

print (ldtp.guiexist ('foo', 'bar'))
```

Unfortunately I get this:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named atomac.ldtpd
Traceback (most recent call last):
  File "/Users/mqm/git/webdriver-python/scratch/ldtp-test.py", line 4, in <module>
    import atomac.ldtp as ldtp
  File "/Users/mqm/venvs/webdriver-python/lib/python2.7/site-packages/atomac/ldtp/__init__.py", line 550, in <module>
    _populateNamespace(globals())
  File "/Users/mqm/venvs/webdriver-python/lib/python2.7/site-packages/atomac/ldtp/__init__.py", line 227, in _populateNamespace
    for method in client._client.system.listMethods():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/Users/mqm/venvs/webdriver-python/lib/python2.7/site-packages/atomac/ldtp/client.py", line 144, in request
    self.send_content(h, request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1456, in send_content
    connection.endheaders(request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 61] Connection refused

Process finished with exit code 1
```

Did I miss anything? Maybe the README can be improved? Thanks in advance!

**Comment by sglebs** [comment]
To be clear: the instructions do not say how to run the LDTP server under McOS. And the LDTP site points back here.

**Comment by muffadaldaginawala** [comment]
I am having the same issue. Did you find a solution to this ?

**Comment by sglebs** [comment]
No. Gave up for now.

**Comment by nagappan** [comment]
Can you try in a terminal like this:

export LDTP_DEBUG=1
ldtp

and from other terminal try running your script and see what is reported in first screen ?
